### ISSUE TITLE
Copr Repo für F33?

### ISSUE THREAD

**Issue by Muku784** [philfry/package-python-axolotl#1]
Hi, könntest Du ein Copr Repo für F33 erstellen?

Ich krieg das F32 nicht zum laufen

`Do you really want to enable copr.fedorainfracloud.org/philfry/gajim? [y/N]: y
Fehler: Diese Paketquelle enthält derzeit keine erstellten Pakete und kann daher nicht aktiviert werden.`

Thx.

**Comment by philfry** [comment]
Hi, ich habe F33 hinzugefügt. Teste es bitte und gib mir Bescheid, ich hab noch F32 laufen.

**Comment by Muku784** [comment]
Hi, danke für die rasche Antwort.

Also `sudo dnf copr enable philfry/gajim` klappt immer noch nicht:

`Do you really want to enable copr.fedorainfracloud.org/philfry/gajim? [y/N]: y
Fehler: Diese Paketquelle enthält derzeit keine erstellten Pakete und kann daher nicht aktiviert werden.`

Ich vermute es sind die builds, die haben noch alle die fc32-Endung:
https://copr.fedorainfracloud.org/coprs/philfry/gajim/builds/

**Comment by Muku784** [comment]
Was funktioniert ist:

`sudo dnf install https://download.copr.fedorainfracloud.org/results/philfry/gajim/fedora-33-x86_64/01726205-python-axolotl/python3-axolotl-0.2.3-2.fc33.noarch.rpm`
`sudo dnf install https://download.copr.fedorainfracloud.org/results/philfry/gajim/fedora-33-x86_64/01726205-python-axolotl/python3-axolotl-0.2.3-2.fc33.noarch.rpm`

**Comment by philfry** [comment]
Hm. Cache gelöscht (`--refresh`)? Die Pakete sehe ich und sie sind auch korrekt benamt:
```
# dnf --disablerepo='*' --enablerepo='copr:copr.fedorainfracloud.org:philfry:gajim' --releasever=32 list available
Copr repo for gajim owned by philfry                                                                                           6.4 kB/s | 6.4 kB     00:00    
Available Packages
python-axolotl.src                                                      0.2.3-2.fc32                               copr:copr.fedorainfracloud.org:philfry:gajim
python-axolotl-curve25519.src                                           0.4.1.2-2.fc32                             copr:copr.fedorainfracloud.org:philfry:gajim
python-axolotl-curve25519-debugsource.x86_64                            0.4.1.2-2.fc32                             copr:copr.fedorainfracloud.org:philfry:gajim
python3-axolotl-curve25519-debuginfo.x86_64                             0.4.1.2-2.fc32                             copr:copr.fedorainfracloud.org:philfry:gajim
# dnf --disablerepo='*' --enablerepo='copr:copr.fedorainfracloud.org:philfry:gajim' --releasever=33 list available
Last metadata expiration check: 0:01:33 ago on Do 29 Okt 2020 14:17:30 CET.
Available Packages
python-axolotl.src                                                      0.2.3-2.fc33                               copr:copr.fedorainfracloud.org:philfry:gajim
python-axolotl-curve25519.src                                           0.4.1.2-2.fc33                             copr:copr.fedorainfracloud.org:philfry:gajim
python-axolotl-curve25519-debugsource.x86_64                            0.4.1.2-2.fc33                             copr:copr.fedorainfracloud.org:philfry:gajim
python3-axolotl-curve25519-debuginfo.x86_64                             0.4.1.2-2.fc33                             copr:copr.fedorainfracloud.org:philfry:gajim
```

**Comment by Muku784** [comment]
Habs jetzt anders gemacht, hab Deinen F33-repo-File kopiert und manuell in `/etc/yum.repos.d/` erstellt und zack, et klappt:

`sudo dnf install gajim python3-axolotl python3-axolotl-curve25519`
`Installiert:
 python3-axolotl-0.2.3-2.fc33.noarch    python3-axolotl-curve25519-0.4.1.2-2.fc33.x86_64    python3-protobuf-3.12.4-1.fc33.noarch`  

Anders krieg ich es jetzt grad nicht hin,  keine Nerven für Fehlersuche. Aber danke für Deine Bemühungen.
