### ISSUE TITLE
Copr release for F36

### ISSUE THREAD

**Issue by orgcontrib** [philfry/package-python-axolotl#3]
Hi @philfry, I hope you'll find some time to read [this](https://discussion.fedoraproject.org/t/philfry-gajim-python-axolotl/37690).

**Comment by philfry** [comment]
Hi, I started a rebuild for F36. Still untested, though, as F36 is not released yet. If there's something missing or broken, please drop me a note.

**Comment by orgcontrib** [comment]
Today I re-enabled the copr repo and dnf no longer complains about it. I think you can close the issue. Thank you!
